//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chofer
    {
        public Chofer()
        {
            this.ViajeChofer = new HashSet<ViajeChofer>();
        }
    
        public int Id { get; set; }
        public string CedulaChofer { get; set; }
        public string Nombre1Chofer { get; set; }
        public string Nombre2Chofer { get; set; }
        public string Apellido1Chofer { get; set; }
        public string Apellido2Chofer { get; set; }
        public string CelularChofer { get; set; }
        public string INSSChofer { get; set; }
        public string DireccionChofer { get; set; }
        public int PaisId { get; set; }
    
        public virtual ICollection<ViajeChofer> ViajeChofer { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
