//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Viaje = new HashSet<Viaje>();
            this.Viaje1 = new HashSet<Viaje>();
            this.Chofer = new HashSet<Chofer>();
        }
    
        public int Id { get; set; }
        public string CodigoPais { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Viaje> Viaje { get; set; }
        public virtual ICollection<Viaje> Viaje1 { get; set; }
        public virtual ICollection<Chofer> Chofer { get; set; }
    }
}
