//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.VehiculoViaje = new HashSet<VehiculoViaje>();
        }
    
        public int Id { get; set; }
        public string PlacaVehiculo { get; set; }
        public string DescripcionVehiculo { get; set; }
        public int TipoDeVehiculoId { get; set; }
        public int MarcaDelVehiculoId { get; set; }
        public int CantidadPasajeros { get; set; }
        public decimal Tonelage { get; set; }
        public string EstadoVehiculo { get; set; }
    
        public virtual TipoDeVehiculo TipoDeVehiculo { get; set; }
        public virtual ICollection<VehiculoViaje> VehiculoViaje { get; set; }
        public virtual MarcaDelVehiculo MarcaDelVehiculo { get; set; }
    }
}
