//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoViaje
    {
        public int Id { get; set; }
        public int VehiculoId { get; set; }
        public int ViajeId { get; set; }
        public Nullable<System.DateTime> FechaHoraSalida { get; set; }
        public Nullable<System.DateTime> FechaHoraLlegada { get; set; }
        public Nullable<System.DateTime> FechaHoraRetorno { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
