//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public Viaje()
        {
            this.ViajeChofer = new HashSet<ViajeChofer>();
            this.VehiculoViaje = new HashSet<VehiculoViaje>();
        }
    
        public int Id { get; set; }
        public string CodigoViaje { get; set; }
        public int CostoViaje { get; set; }
        public int PagoChoferViaje { get; set; }
        public string DescripcionViaje { get; set; }
        public int TipoDeViajeId { get; set; }
        public int ProveedorId { get; set; }
        public int ChoferId { get; set; }
        public int PaisId { get; set; }
        public int PaisId1 { get; set; }
        public int CantidadPasajeros { get; set; }
        public decimal Tonelage { get; set; }
    
        public virtual TipoDeViaje TipoDeViaje { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<ViajeChofer> ViajeChofer { get; set; }
        public virtual ICollection<VehiculoViaje> VehiculoViaje { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pais Pais1 { get; set; }
    }
}
