//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.GestionUsuario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.FuncionAsignada = new HashSet<FuncionAsignada>();
        }
    
        public int Id { get; set; }
        public string NombreDeUsuario { get; set; }
        public string ClaveDeUsuario { get; set; }
    
        public virtual ICollection<FuncionAsignada> FuncionAsignada { get; set; }
    }
}
